import com.google.common.collect.Lists;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import model.DownstreamHttpMessages;
import model.DownstreamHttpResponse;
import util.EnvironmentVariableManager;
import util.ObjectMapperImpl;

import java.util.Optional;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jason' at '12/23/16 12:56 AM' with Gradle 3.1
 *
 * @author jason, @date 12/23/16 12:56 AM
 */
public class FcmSender {

  private final String fcmServerUrl = "https://fcm.googleapis.com/fcm/send";
  private final String authKey;

  public FcmSender(String authKey) {
    this.authKey = authKey;
  }

  public DownstreamHttpResponse sendNotification(DownstreamHttpMessages downstreamHttpMessages) throws UnirestException {
    Unirest.setObjectMapper(new ObjectMapperImpl());
    HttpResponse<DownstreamHttpResponse> response =
        Unirest.post(fcmServerUrl)
            .header("Content-Type", "application/json")
            .header("Authorization", authKey)
            .body(downstreamHttpMessages)
            .asObject(DownstreamHttpResponse.class);
    DownstreamHttpResponse downstreamHttpResponse = response.getBody();
    return downstreamHttpResponse;
  }
}
