import com.google.common.collect.Lists;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;

import model.DownstreamHttpMessages;
import model.DownstreamHttpResponse;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jason' at '12/23/16 12:56 AM' with Gradle 3.1
 *
 * @author jason, @date 12/23/16 12:56 AM
 */
public class Library {
  public DownstreamHttpResponse someLibraryMethod() throws UnirestException {
    Unirest.setObjectMapper(new ObjectMapperImpl());

    HttpResponse<DownstreamHttpResponse> response =
        Unirest.post("https://fcm.googleapis.com/fcm/send")
            .header("Content-Type", "application/json")
            .header(
                "Authorization",
                "...")
            .body(
                new DownstreamHttpMessages(
                    "...",
                    Lists.newArrayList()))
            .asObject(DownstreamHttpResponse.class);
    DownstreamHttpResponse downstreamHttpResponse = response.getBody();
    return downstreamHttpResponse;
  }
}
