/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jason' at '12/23/16 12:56 AM' with Gradle 3.1
 *
 * @author jason, @date 12/23/16 12:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
