import com.google.common.collect.Lists;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import model.DownstreamHttpMessages;
import model.DownstreamHttpResponse;
import util.EnvironmentVariableManager;
import util.ObjectMapperImpl;

import java.util.Optional;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jason' at '12/23/16 12:56 AM' with Gradle 3.1
 *
 * @author jason, @date 12/23/16 12:56 AM
 */
public class Library {

  private final String environmentAuthKey = "AUTH_KEY";

  public DownstreamHttpResponse sendNotification(String registrationToken) throws UnirestException {
    Optional<String> authKeyOptional =
        EnvironmentVariableManager.getInstance().getEnvironmentVariable(environmentAuthKey);
    if (!authKeyOptional.isPresent()) {
      // TODO: throw exception!
    }
    Unirest.setObjectMapper(new ObjectMapperImpl());
    HttpResponse<DownstreamHttpResponse> response =
        Unirest.post("https://fcm.googleapis.com/fcm/send")
            .header("Content-Type", "application/json")
            .header("Authorization", authKeyOptional.get())
            .body(new DownstreamHttpMessages(registrationToken, Lists.newArrayList()))
            .asObject(DownstreamHttpResponse.class);
    DownstreamHttpResponse downstreamHttpResponse = response.getBody();
    return downstreamHttpResponse;
  }
}
