import com.mashape.unirest.http.exceptions.UnirestException;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jason' at '12/23/16 12:56 AM' with Gradle 3.1
 *
 * @author jason, @date 12/23/16 12:56 AM
 */
public class FcmSenderTest {

  @Test
  public void testSomeLibraryMethod() throws UnirestException {
//    FcmSender classUnderTest = new FcmSender();
//    System.err.println(classUnderTest.sendNotification("").toString());
//    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
