import com.mashape.unirest.http.exceptions.UnirestException;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jason' at '12/23/16 12:56 AM' with Gradle 3.1
 *
 * @author jason, @date 12/23/16 12:56 AM
 */
public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() throws UnirestException {
    Library classUnderTest = new Library();
    System.err.println(classUnderTest.someLibraryMethod().toString());
//    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
